Installing faahKO requires xcms to be installed first. Otherwise, the installtion fails with:
  ** preparing package for lazy loading
  Error in loadNamespace(name) : there is no package called 'xcms'
  ERROR: lazy loading failed for package ‘faahKO’

This is because the dataset stored in faahKO is an instance of an S4
class defined in xcms.


git-svn-id: file:///home/git/bioc-data.hedgehog.fhcrc.org/trunk/experiment/pkgs/faahKO@1544 db2202da-8704-0410-b924-b125b3cd84ef